# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support_staff', '0001_initial'),
        ('orders_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('date_published', models.DateTimeField()),
                ('last_change', models.DateTimeField()),
                ('date_closed', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Resolved'), (2, 'Waiting'), (3, 'Processing'), (4, 'Canceled')])),
                ('assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_staff.Staff')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_management.Order')),
            ],
        ),
    ]
