# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('support_staff', '0001_initial'),
        ('orders_management', '0002_auto_20170704_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_staff.Staff'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_management.Order'),
        ),
    ]
