# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
