# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('description', models.TextField()),
                ('discount', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('FO', 'Fixed Amount Off Cart Value'), ('PO', 'Percentage Off Cart Value'), ('FP', 'Fixed Amount Off Product'), ('PP', 'Percentage Off Product')], max_length=2)),
                ('usage_cap', models.PositiveSmallIntegerField()),
                ('per_user', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.Coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_management.Order')),
            ],
        ),
    ]
